version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '20:00'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/packages/fs'
    schedule:
      interval: daily
      time: '20:00'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/packages/eslint-config-ts'
    schedule:
      interval: daily
      time: '20:00'
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: '/packages/eslint-config-react'
    schedule:
      interval: daily
      time: '20:00'
    open-pull-requests-limit: 10
